services:

  redis:
    image: redis:7
    container_name: twitter-clone-redis

  api:
    build:
      context: ./twitter-clone-backend
      dockerfile: Dockerfile
    image: twitter-clone-api
    container_name: twitter-clone-api
    volumes:	    
      - /var/www/hazemgamal.uk.to/media:/project/media
    ports:
      - 8000:8000

  frontend:
    build:
      context: ./twitter-clone-frontend
      dockerfile: Dockerfile
    image: twitter-clone-frontend
    container_name: twitter-clone-frontend
    ports:
      - 8080:80
    volumes:
      - /var/www/hazemgamal.uk.to/media:/usr/share/nginx/media

volumes:
  frontend-build:
    name: frontend-build-vol
  twitter-clone-media:
    name: twitter-clone-media
